name: Docker Image CI

on:
    push:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: docker login
              env:
                  DOCKER_USER: jackbailey
                  DOCKER_PASS: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
              run: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASS
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag jackbailey/simplecontact
            - name: Docker Push
              run: docker push jackbailey/simplecontact
